# Generated by Django 3.2.6 on 2021-09-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rId', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=100)),
                ('sName', models.CharField(max_length=100)),
                ('eMail', models.CharField(max_length=200)),
            ],
        ),
    ]
